
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[446] =
    {   0,
        0,    0,   54,   53,   37,   44,   49,   53,   39,   40,
       53,   53,   53,   38,   42,   48,    1,   43,   43,   43,
       43,   43,   43,   41,   43,   43,   43,   43,   43,   43,
       43,    0,    0,    0,    0,    0,    0,   37,    0,   52,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    3,   47,    0,   47,   46,    2,
        4,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   14,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   51,   47,    0,

       50,   45,   45,   45,   45,   45,   45,   45,   45,   19,
       45,   45,   20,   45,   45,   45,   45,   45,   45,    8,
        7,   45,   30,    0,    0,    0,    0,    0,    0,   30,
        0,    0,    0,    0,    0,    0,   30,   45,   45,   45,
       45,   45,   45,   18,   45,   45,   45,   21,   45,   45,
       45,   10,   45,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   45,
       45,   45,   45,   45,   45,   45,   45,   16,   45,   45,
        6,   45,   45,   45,   45,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       17,    5,   45,   45,   45,    0,    0,   28,   26,    0,
       27,   29,    0,    0,    0,    0,   28,   26,    0,   27,
       29,    0,    0,   45,   45,   28,   26,   45,   27,   29,
       45,   45,   45,    9,   45,   45,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   15,   45,   45,   45,   24,    0,    0,
        0,    0,    0,    0,    0,    0,   24,    0,    0,    0,
        0,    0,    0,    0,    0,   24,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   45,    0,   33,    0,
       31,    0,    0,    0,    0,    0,   33,    0,   31,    0,
        0,    0,    0,   45,   33,   45,   31,   45,   45,   45,
       45,   45,   45,   13,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   45,   45,   45,   45,
       45,   45,   45,   12,   22,   25,    0,   32,    0,    0,
       22,   25,    0,   32,    0,    0,   22,   25,   45,   32,
       45,   45,   45,    0,    0,    0,    0,    0,    0,   45,
       45,   45,   45,    0,    0,    0,    0,    0,    0,    0,
        0,   45,   45,   45,   45,   11,   23,    0,    0,    0,

       23,    0,    0,    0,   23,   45,   45,   45,    0,    0,
        0,    0,    0,    0,   45,   45,   45,    0,    0,    0,
        0,    0,    0,   45,   45,   45,    0,   34,   36,    0,
       34,   36,   45,   34,   36,    0,    0,   45,    0,    0,
       45,   35,   35,   35,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    1,    1,    1,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   13,    1,
       14,   15,    1,    1,   16,   16,   16,   17,   18,   16,
       16,   16,   16,   16,   19,   20,   21,   22,   23,   24,
       16,   25,   26,   27,   16,   28,   29,   16,   16,   16,
        1,   30,    1,    1,   31,    1,   32,   16,   33,   34,

       35,   36,   37,   38,   39,   16,   16,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   16,   16,
       51,   16,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[52] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    2,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3
    } ;

static yyconst flex_int16_t yy_base[450] =
    {   0,
        0,    0,  817,   20,   52,  818,   96,   25,   43,   60,
       72,   91,  112,  151,  118,  120,  102,  139,  156,  168,
      173,  199,   43,  190,  190,   98,  205,  206,  217,  221,
      222,   25,  776,  776,  770,  778,  769,  809,   51,  818,
      106,  244,  117,  110,  166,  220,  254,  805,  173,   57,
       55,   68,   96,  125,  818,  798,  805,  796,  165,  818,
      818,    0,   30,  766,  766,  760,  768,  759,  754,   36,
      169,  134,    0,  752,  753,  757,  749,  137,  761,  748,
      215,  750,  761,  758,  747,  747,  747,  753,  746,  740,
      245,  257,  260,  262,  263,  264,  269,  818,  774,  781,

      818,  749,  738,  738,  738,  744,  737,  731,  728,  731,
      732,  729,    0,  737,  736,  735,  736,  230,  721,    0,
        0,  721,  156,  731,  718,  730,  721,  719,  713,  272,
      276,  277,  278,  279,  287,  296,  296,  725,  712,  724,
      715,  713,  707,    0,  706,  718,  717,    0,  705,  718,
      701,  725,  699,  711,  699,  702,  708,  717,  706,  690,
      713,  306,  310,  312,  315,  318,  323,  319,  321,  703,
      691,  694,  700,  709,  698,  682,  705,    0,  684,  681,
        0,  680,  692,  680,  678,  684,  680,  688,  687,  677,
      685,  683,  152,  325,  327,  329,  330,  331,  342,  348,

      358,  677,  673,  681,  680,  670,  678,  676,  247,  662,
        0,    0,  663,  690,  678,  674,  661,  818,  818,  655,
      818,  349,  660,  661,  363,  371,  375,  376,  377,  378,
      394,  380,  386,  669,  656,    0,    0,  650,    0,  375,
      655,  656,  645,  672,  649,  654,  641,  656,  642,  654,
      653,  641,  654,  639,  640,  382,  400,  398,  410,  413,
      417,  421,  425,  428,  632,  647,  633,  645,  644,  632,
      645,  630,  631,    0,  628,  624,  624,  818,  625,  635,
      629,  617,  624,  626,  617,  624,  427,  430,  432,  434,
      435,  438,  440,  445,  448,    0,  617,  627,  621,  609,

      616,  618,  609,  616,  637,  622,  615,  604,  818,  619,
      818,  606,  600,  613,  612,  452,  455,  457,  462,  465,
      469,  473,  475,  598,    0,  613,    0,  600,  594,  607,
      602,  586,  590,    0,  577,  575,  589,  588,  574,  573,
      486,  487,  490,  492,  493,  494,  567,  566,  581,  580,
      567,  564,  561,    0,  818,  818,  560,  818,  556,  535,
      498,  500,  502,  503,  509,  515,    0,    0,  536,    0,
      525,  523,  530,  511,  504,  506,  522,  530,  531,  467,
      519,  489,  472,  460,  462,  441,  440,  538,  539,  542,
      545,  403,  411,  398,  394,    0,  818,  373,  370,  360,

      546,  547,  549,  550,    0,  353,  342,  340,  339,  337,
      323,  554,  560,  561,  291,  290,  289,  300,  293,  283,
      563,  562,  570,  263,  242,  237,  187,  818,  818,  577,
      582,  583,  176,    0,    0,  160,  592,  102,   90,  597,
       48,  818,  599,    0,  818,  632,  635,   74,  638
    } ;

static yyconst flex_int16_t yy_def[450] =
    {   0,
      445,    1,  445,  445,  445,  445,  446,  447,  445,  445,
      445,  445,  445,  445,  445,  445,   14,  448,  448,  448,
      448,  448,   22,  445,   22,   22,   22,   22,   22,   22,
       22,  445,  445,  445,  445,  445,  445,  445,  446,  445,
      445,  446,  446,  446,  446,  446,  446,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  449,  445,  445,  445,
      445,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  445,  445,  445,  445,  445,  445,  445,
      446,  446,  446,  446,  446,  446,  446,  445,  445,  449,

      445,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  445,  445,  445,  445,  445,  445,  445,  446,
      446,  446,  446,  446,  446,  446,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  445,  445,  445,  445,  445,  445,  445,
      445,  446,  446,  446,  446,  446,  446,  446,  446,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  445,  445,  445,  445,  445,
      445,  445,  445,  446,  446,  446,  446,  446,  446,  446,

      446,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  448,  448,  448,  448,  448,

      448,  448,  448,  448,  448,  448,  448,  445,  445,  445,
      445,  445,  445,  445,  445,  446,  446,  446,  446,  446,
      446,  446,  446,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  445,  445,  445,  445,  445,  445,
      446,  446,  446,  446,  446,  446,  448,  448,  448,  448,
      448,  448,  448,  448,  445,  445,  445,  445,  445,  445,
      446,  446,  446,  446,  446,  446,  448,  448,  448,  448,
      448,  448,  448,  445,  445,  445,  446,  446,  446,  448,
      448,  448,  448,  445,  445,  445,  445,  446,  446,  446,
      446,  448,  448,  448,  448,  448,  445,  445,  445,  445,

      446,  446,  446,  446,  448,  448,  448,  448,  445,  445,
      445,  446,  446,  446,  448,  448,  448,  445,  445,  445,
      446,  446,  446,  448,  448,  448,  445,  445,  445,  446,
      446,  446,  448,  448,  448,  445,  446,  448,  445,  446,
      448,  445,  446,  448,    0,  445,  445,  445,  445
    } ;

static yyconst flex_int16_t yy_nxt[870] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,    4,   18,   18,   18,   18,   19,
       20,   18,   18,   21,   18,   22,   23,   18,   18,    4,
       24,   25,   26,   18,   18,   18,   27,   18,   18,   28,
       18,   29,   18,   18,   18,   30,   31,   18,   18,   18,
       18,   32,   33,   38,   40,   34,   49,   50,   84,   98,
       51,   98,   35,  102,   62,   36,   37,   52,   85,  102,
       53,   54,   98,  103,   32,   33,   62,   62,   34,  110,
       41,   76,  444,   32,   33,   35,   55,   34,   36,   37,
       62,   32,   33,   87,   35,   34,   86,   36,   37,   40,

       98,   56,   35,   32,   33,   36,   37,   34,   39,   39,
      445,   88,  445,   40,   35,   60,   61,   36,   37,   62,
       40,   57,   32,   33,  442,   41,   34,   42,   43,   98,
       89,   44,   62,   35,  441,   39,   36,   37,   45,   41,
       78,   46,   47,   32,   33,   62,   41,   34,   94,   32,
       33,   32,   33,   34,   35,   34,   93,   36,   37,   58,
       35,   59,   35,   36,   37,   36,   37,   90,  107,   40,
       63,   64,  154,   58,   65,   59,  112,   98,  117,  155,
      106,   66,   32,   33,   67,   68,   34,   63,   64,  223,
      224,   65,  439,   35,   69,   41,   36,   37,   66,   70,

       64,   67,   68,   65,   63,   64,   84,  111,   65,   95,
       66,   62,  106,   67,   68,   71,   85,  438,   72,   68,
       73,   32,   33,   40,   62,   34,   62,   62,  436,   77,
       63,   64,   35,   74,   65,   36,   37,   62,   62,   62,
       80,   66,   62,   62,   67,   68,   75,   40,   40,   41,
       79,   62,   62,   62,   96,   82,   62,   40,  106,   81,
       40,  151,  120,   40,   62,   40,   40,   40,   62,   83,
      142,  435,   40,   41,   41,   40,  434,   91,  130,   40,
       40,   40,   40,   41,  241,  242,   41,   92,  162,   41,
       40,   41,   41,   41,  433,  163,   97,  134,   41,   40,

      131,   41,  132,  133,  135,   41,   41,   41,   41,   40,
      164,  166,  170,   40,  136,   40,   41,  429,   40,  171,
      167,   40,   40,  165,   40,   41,   40,  428,   40,  168,
       40,  427,   40,   40,   40,   41,  426,  425,  424,   41,
      194,   41,  198,  169,   41,   40,  201,   41,   41,  197,
       41,   40,   41,  196,   41,  195,   41,  199,   41,   41,
       41,   40,  227,  228,  225,  250,   40,  251,  200,  226,
      420,   41,  252,  229,   40,  230,  253,   41,   40,   40,
       40,   40,  231,   40,  419,   40,  418,   41,  417,   40,
      416,  268,   41,  269,  256,  232,  233,   40,  270,  415,

       41,   40,  271,   40,   41,   41,   41,   41,  411,   41,
      259,   41,  260,   40,  257,   41,   40,  261,  410,  409,
       40,  262,  263,   41,   40,  258,  264,   41,   40,   41,
       40,   40,  287,   40,  288,   40,  408,   40,   40,   41,
      407,   40,   41,   40,  290,  289,   41,  291,   40,  406,
       41,   40,  293,  405,   41,   40,   41,   41,   40,   41,
       40,   41,  292,   41,   41,   40,  317,   41,   40,   41,
      294,  295,   40,  318,   41,  316,   40,   41,   40,  321,
      320,   41,  400,  399,   41,  319,   41,  323,  342,   40,
       40,   41,  322,   40,   41,   40,   40,   40,   41,  341,

      398,   40,   41,   40,   41,   40,   40,  345,  343,  346,
      397,  396,   40,  395,  392,   41,   41,  344,   40,   41,
      385,   41,   41,   41,  363,   40,  364,   41,  386,   41,
      387,   41,   41,   40,   40,  393,  361,  362,   41,  365,
      366,   40,   40,  394,   41,   40,  389,  377,   40,   40,
       40,   41,   40,   40,  390,  391,  378,   40,  384,   41,
       41,  383,  379,   40,   40,   40,   40,   41,   41,  388,
      382,   41,  381,   40,   41,   41,   41,  402,   41,   41,
       40,  380,  376,   41,  403,   40,   40,  404,  401,   41,
       41,   41,   41,  412,  430,   40,  431,  413,  414,   41,

       40,  421,   40,  375,  432,  374,   41,  422,  423,  373,
      372,   41,   41,  371,  370,  369,  368,  367,  437,  360,
      359,   41,  358,  357,  440,  356,   41,  355,   41,  354,
      353,  443,   39,   39,   39,   48,  352,   48,  100,  100,
      100,  351,  350,  349,  348,  347,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  315,  314,  313,  312,  311,  310,  309,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  267,  266,

      265,  255,  254,  249,  248,  247,  246,  245,  244,  243,
      240,  239,  238,  237,  236,  235,  234,  222,  221,  220,
      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  202,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      161,  160,  159,  158,  157,  156,  153,  152,  150,  149,
      148,  147,  146,  145,  138,  144,  143,  142,  141,  140,
      139,  138,  137,  101,   99,  129,  128,  127,  126,  125,
      124,  123,  122,  121,  119,  118,  116,  115,  114,  113,

      109,  108,  107,  106,  105,  104,   99,  101,   99,   98,
       38,   90,   89,   88,   87,   86,  445,    3,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445
    } ;

static yyconst flex_int16_t yy_chk[870] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    4,    5,   39,    4,    8,    8,   32,   51,
        8,   50,    4,   63,   23,    4,    4,    8,   32,   70,
        8,    8,   52,   63,    9,    9,  448,   23,    9,   70,
       39,   23,  441,    5,    5,    9,   11,    5,    9,    9,
       23,   10,   10,   51,    5,   10,   50,    5,    5,    7,

       53,   12,   10,   11,   11,   10,   10,   11,   41,   41,
       17,   52,   17,   44,   11,   17,   17,   11,   11,   26,
       43,   13,   12,   12,  439,    7,   12,    7,    7,   54,
       53,    7,   26,   12,  438,   41,   12,   12,    7,   44,
       26,    7,    7,   13,   13,   26,   43,   13,   44,   15,
       15,   16,   16,   15,   13,   16,   43,   13,   13,   14,
       15,   14,   16,   15,   15,   16,   16,   54,   72,   45,
       18,   18,  123,   59,   18,   59,   72,   49,   78,  123,
       78,   18,   14,   14,   18,   18,   14,   19,   19,  193,
      193,   19,  436,   14,   19,   45,   14,   14,   19,   20,

       20,   19,   19,   20,   21,   21,   49,   71,   21,   45,
       20,   25,   71,   20,   20,   21,   49,  433,   21,   21,
       22,   24,   24,   46,   25,   24,   27,   28,  427,   25,
       22,   22,   24,   22,   22,   24,   24,   25,   29,   27,
       28,   22,   30,   31,   22,   22,   22,   42,   91,   46,
       27,   29,   27,   28,   46,   30,   31,   47,   81,   29,
       92,  118,   81,   93,   29,   94,   95,   96,   30,   31,
      118,  426,   97,   42,   91,  130,  425,   42,   91,  131,
      132,  133,  134,   47,  209,  209,   92,   42,  130,   93,
      135,   94,   95,   96,  424,  130,   47,   95,   97,  136,

       92,  130,   93,   94,   96,  131,  132,  133,  134,  162,
      131,  133,  137,  163,   97,  164,  135,  420,  165,  137,
      134,  166,  168,  132,  169,  136,  167,  419,  194,  135,
      195,  418,  196,  197,  198,  162,  417,  416,  415,  163,
      162,  164,  166,  136,  165,  199,  169,  166,  168,  165,
      169,  200,  167,  164,  194,  163,  195,  167,  196,  197,
      198,  201,  196,  197,  194,  222,  225,  222,  168,  195,
      411,  199,  222,  198,  226,  199,  222,  200,  227,  228,
      229,  230,  200,  232,  410,  256,  409,  201,  408,  233,
      407,  240,  225,  240,  225,  201,  201,  231,  240,  406,

      226,  258,  240,  257,  227,  228,  229,  230,  400,  232,
      231,  256,  231,  259,  226,  233,  260,  231,  399,  398,
      261,  231,  232,  231,  262,  229,  233,  258,  263,  257,
      287,  264,  256,  288,  257,  289,  395,  290,  291,  259,
      394,  292,  260,  293,  259,  258,  261,  260,  294,  393,
      262,  295,  262,  392,  263,  316,  287,  264,  317,  288,
      318,  289,  261,  290,  291,  319,  289,  292,  320,  293,
      263,  264,  321,  290,  294,  288,  322,  295,  323,  293,
      292,  316,  387,  386,  317,  291,  318,  295,  318,  341,
      342,  319,  294,  343,  320,  344,  345,  346,  321,  316,

      385,  361,  322,  362,  323,  363,  364,  322,  320,  323,
      384,  383,  365,  382,  380,  341,  342,  321,  366,  343,
      375,  344,  345,  346,  343,  377,  344,  361,  375,  362,
      376,  363,  364,  378,  379,  381,  341,  342,  365,  345,
      346,  388,  389,  381,  366,  390,  378,  363,  391,  401,
      402,  377,  403,  404,  378,  379,  365,  412,  374,  378,
      379,  373,  366,  413,  414,  422,  421,  388,  389,  377,
      372,  390,  371,  423,  391,  401,  402,  389,  403,  404,
      430,  369,  360,  412,  390,  431,  432,  391,  388,  413,
      414,  422,  421,  402,  421,  437,  422,  403,  404,  423,

      440,  412,  443,  359,  423,  357,  430,  413,  414,  353,
      352,  431,  432,  351,  350,  349,  348,  347,  430,  340,
      339,  437,  338,  337,  437,  336,  440,  335,  443,  333,
      332,  440,  446,  446,  446,  447,  331,  447,  449,  449,
      449,  330,  329,  328,  326,  324,  315,  314,  313,  312,
      310,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  286,  285,  284,  283,  282,  281,  280,
      279,  277,  276,  275,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  238,  235,

      234,  224,  223,  220,  217,  216,  215,  214,  213,  210,
      208,  207,  206,  205,  204,  203,  202,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  180,  179,
      177,  176,  175,  174,  173,  172,  171,  170,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  147,  146,  145,  143,  142,  141,  140,  139,  138,
      129,  128,  127,  126,  125,  124,  122,  119,  117,  116,
      115,  114,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  100,   99,   90,   89,   88,   87,   86,
       85,   84,   83,   82,   80,   79,   77,   76,   75,   74,

       69,   68,   67,   66,   65,   64,   58,   57,   56,   48,
       38,   37,   36,   35,   34,   33,    3,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pl_lex.l"
#line 787 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 61 "pl_lex.l"

#line 971 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 446 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 818 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "pl_lex.l"
printf("<ASSIGN>");
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 63 "pl_lex.l"
printf("<BOOLCHECK>");
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "pl_lex.l"
printf("<ONEWAY>");
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "pl_lex.l"
printf("<TWOWAY>");
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "pl_lex.l"
printf("<CONCAT>");
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "pl_lex.l"
printf("<ALTER>");
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "pl_lex.l"
printf("<REP>");
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "pl_lex.l"
printf("<NOT>");
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "pl_lex.l"
printf("<GREATER>");
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "pl_lex.l"
printf("<LESS>");
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "pl_lex.l"
printf("<GREATEROREQUAL>");
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "pl_lex.l"
printf("<LESSOREQUAL>");
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "pl_lex.l"
printf("<STARTSWITH>");
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 77 "pl_lex.l"
printf("<STREETNETWORK>");
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 78 "pl_lex.l"
printf("<PROPERTY>");
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 79 "pl_lex.l"
printf("<POINT>");
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "pl_lex.l"
printf("<STREET>");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 81 "pl_lex.l"
printf("<LIST>");
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 82 "pl_lex.l"
printf("<MAP>");
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 83 "pl_lex.l"
printf("<SET>");
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 84 "pl_lex.l"
printf("<TIME>");
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 85 "pl_lex.l"
printf("<ADDPROPERTY>");
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 86 "pl_lex.l"
printf("<REMOVEPROPERTY>");
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 87 "pl_lex.l"
printf("<ADDDELAY>");
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 88 "pl_lex.l"
printf("<REMOVEDELAY>");
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 89 "pl_lex.l"
printf("<CLOSED>");
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 90 "pl_lex.l"
printf("<OPENED>");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 91 "pl_lex.l"
printf("<APPEND>");
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 92 "pl_lex.l"
printf("<REMOVE>");
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 93 "pl_lex.l"
printf("<ADD>");
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 94 "pl_lex.l"
printf("<REMOVEKEY>");
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 95 "pl_lex.l"
printf("<REMOVEVALUE>");
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 96 "pl_lex.l"
printf("<FINDROUTE>");
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 97 "pl_lex.l"
printf("<SORTSHORTESTROUTE>");
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 98 "pl_lex.l"
printf("<SORTSHORTESTDISTANCE>");
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 99 "pl_lex.l"
printf("<SORTSIMPLESTROUTE>");
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "pl_lex.l"
printf("");
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 102 "pl_lex.l"
printf("<DIGIT>");
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 103 "pl_lex.l"
printf("<LPARAN>");
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 104 "pl_lex.l"
printf("<RPARAN>");
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 105 "pl_lex.l"
printf("<UNDERSCORE>");
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 106 "pl_lex.l"
printf("<COLON>");
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 107 "pl_lex.l"
printf("<LETTER>");
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 108 "pl_lex.l"
printf("\n");
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 110 "pl_lex.l"
printf("<ID,%s>",yytext);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 111 "pl_lex.l"
printf("<INT>");
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 112 "pl_lex.l"
printf("<FLOAT,%s>",yytext);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "pl_lex.l"
printf("<ENDSTATEMENT>");
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "pl_lex.l"
printf("<QUOTATION>");
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 115 "pl_lex.l"
printf("<COMMENT>\n");
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 116 "pl_lex.l"
printf("<CHARACTER,%s>",yytext);
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 117 "pl_lex.l"
printf("<STRING,%s>",yytext);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 120 "pl_lex.l"
ECHO;
	YY_BREAK
#line 1323 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 446 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 446 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 445);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 120 "pl_lex.l"



int main() { 
  yylex();
  return 0; 
}

